const IntrinsicElements: Array<keyof JSX.IntrinsicElements> = [
  'symbol',
  // 'object',
  'small',
  'button',
  'a',
  'abbr',
  'address',
  // 'area', - Void element - cannot accept Children
  'article',
  'aside',
  'audio',
  'b',
  // 'base', - Void element - cannot accept Children
  'bdi',
  'bdo',
  'big',
  'blockquote',
  'body',
  // 'br', - Void element - cannot accept Children
  'canvas',
  'caption',
  'cite',
  'code',
  // 'col', - Void element - cannot accept Children
  'colgroup',
  'data',
  'datalist',
  'dd',
  'del',
  'details',
  'dfn',
  'dialog',
  'div',
  'dl',
  'dt',
  'em',
  // 'embed', - Void element - cannot accept Children
  'fieldset',
  'figcaption',
  'figure',
  'footer',
  'form',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'head',
  'header',
  'hgroup',
  // 'hr', - Void element - cannot accept Children
  'html',
  'i',
  'iframe',
  // 'img', - Void element - cannot accept Children
  // 'input', - Void element - cannot accept Children
  'ins',
  'kbd',
  'keygen',
  'label',
  'legend',
  'li',
  // 'link', - Void element - cannot accept Children
  'main',
  'map',
  'mark',
  'menu',
  'menuitem',
  // 'meta', - Void element - cannot accept Children
  'meter',
  'nav',
  'noindex',
  'noscript',
  'ol',
  'optgroup',
  'option',
  'output',
  'p',
  'param',
  'picture',
  'pre',
  'progress',
  'q',
  'rp',
  'rt',
  'ruby',
  's',
  'samp',
  'slot',
  'script',
  'section',
  'select',
  // 'source', - Void element - cannot accept Children
  'span',
  'strong',
  'style',
  'sub',
  'summary',
  'sup',
  'table',
  'template',
  'tbody',
  'td',
  'textarea',
  'tfoot',
  'th',
  'thead',
  'time',
  'title',
  'tr',
  // 'track', - Void element - cannot accept Children
  'u',
  'ul',
  'var',
  'video',
  // 'wbr', - Void element - cannot accept Children
  'webview',
  'svg'
];

export default IntrinsicElements;
