export const storybookExcludedControlParams = [
  'aria-controls',
  'aria-describedby',
  'aria-label',
  'aria-labelledby',
  'aria-describedby',
  'className',
  'id',
  'onBlur',
  'onCancel',
  'onChange',
  'onClear',
  'onClick',
  'onConfirm',
  'onDismiss',
  'onFilter',
  'popoverZIndex',
  'portalClassName',
  'portalContainer',
  'ref',
  'setOpen',
  'scrollContainer',
  'usePortal',
] as const;
