packages:
  # all packages in direct subdirectories of apps/, charts/, chat/, packages/, & tools/
  - 'apps/*'
  - 'charts/*'
  - 'chat/*'
  - 'mcp-ui/*'
  - 'packages/*'
  - 'tools/*'

catalog:
  lodash: ^4.17.21
