packages:
  # all packages in direct subdirectories of apps/, charts/, chat/, packages/, & tools/
  - 'apps/*'
  - 'charts/*'
  - 'chat/*'
  - 'mcp-ui/*'
  - 'packages/*'
  - 'tools/*'

catalog:
  lodash: ^4.17.21
  polished: ^4.2.2
  prettier: ^2.8.8
