packages:
  # all packages in direct subdirectories of apps/, charts/, chat/, packages/, & tools/
  - 'apps/*'
  - 'charts/*'
  - 'chat/*'
  - 'mcp-ui/*'
  - 'packages/*'
  - 'tools/*'

catalog:
  lodash: ^4.17.21
  polished: ^4.2.2
  prettier: ^2.8.8
  react-transition-group: ^4.4.5
  '@faker-js/faker': ^8.4.1

  # Build dependencies
  '@babel/core': 7.24.3

  # CLI dependencies
  chalk: 4.1.2
  '@types/cross-spawn': 6.0.2
  cross-spawn: 7.0.3
  '@types/fs-extra': 11.0.1
  fs-extra: 11.1.1
  glob: ^10.3.12
