import { DRAWER_TOOLBAR_WIDTH } from '../constants';

export const HEADER_HEIGHT = 48;
export const MOBILE_BREAKPOINT = 390;
export const DRAWER_MAX_WIDTH = 612;
export const DRAWER_MAX_WIDTH_WITH_TOOLBAR =
  DRAWER_MAX_WIDTH - DRAWER_TOOLBAR_WIDTH;
export const DRAWER_MIN_WIDTH = 320;
export const DRAWER_MIN_WIDTH_WITH_TOOLBAR =
  DRAWER_MIN_WIDTH - DRAWER_TOOLBAR_WIDTH;
export const DRAWER_MAX_PERCENTAGE_WIDTH = 50;
