export { pkgJson } from './package.json';
export { readMe } from './readme.md';
export { tsConfig } from './tsconfig.json';
export { index } from './src/index.template';
export { componentIndex } from './src/Component/component.index.template';
export { component } from './src/Component/component.template';
export { spec } from './src/Component/component.spec.template';
export { types } from './src/Component/component.types.template';
export { styles } from './src/Component/component.styles.template';
