const Components = {
  Badge: 'badge',
  Banner: 'banner',
  Button: 'button',
  Box: 'box',
  Callout: 'callout',
  Card: 'card',
  Checkbox: 'checkbox',
  Code: 'code',
  ConfirmationModal: 'confirmation-modal',
  Copyable: 'copyable',
  Icon: 'icon',
  IconButton: 'icon-button',
  InlineDefinition: 'inline-definition',
  Logo: 'logo',
  MarketingModal: 'marketing-modal',
  Menu: 'menu',
  Modal: 'modal',
  MongoNav: 'mongo-nav',
  Palette: 'palette',
  Pipeline: 'pipeline',
  Popover: 'popover',
  Portal: 'portal',
  RadioBoxGroup: 'radio-box-group',
  RadioGroup: 'radio-group',
  SideNav: 'side-nav',
  Stepper: 'stepper',
  Syntax: 'syntax',
  Table: 'table',
  Tabs: 'tabs',
  TextArea: 'text-area',
  TextInput: 'text-input',
  Toast: 'toast',
  Toggle: 'toggle',
  Tokens: 'tokens',
  Tooltip: 'tooltip',
  Typography: 'typography',
} as const;

type Components = typeof Components[keyof typeof Components];

export default Components;
