export const defaultData = [
  {
    name: 'Alice',
    age: 19,
    color: 'blue',
    location: 'bedford',
    rand: Math.random(),
  },
  {
    name: 'Brooke',
    age: 20,
    color: 'green',
    location: 'bedford',
    rand: Math.random(),
  },
  {
    name: 'Charlotte',
    age: 21,
    color: 'white',
    location: 'bedford',
    rand: Math.random(),
    disabled: true,
  },
  {
    name: 'Donna',
    age: 22,
    color: 'green',
    location: 'bedford',
    rand: Math.random(),
  },
  {
    name: 'Emma',
    age: 23,
    color: 'white',
    location: 'bedford',
    rand: Math.random(),
  },
  {
    name: 'Georgia',
    age: 24,
    color: 'white',
    location: 'bedford',
    rand: Math.random(),
  },
  {
    name: 'Frannie',
    age: 29,
    color: 'green',
    location: 'bedford',
    rand: Math.random(),
  },
  {
    name: 'Iman',
    age: 26,
    color: 'white',
    location: 'bedford',
    rand: Math.random(),
  },
  {
    name: 'Hannah',
    age: 27,
    color: 'green',
    location: 'bedford',
    rand: Math.random(),
  },
  {
    name: 'Jill',
    age: 28,
    color: 'green',
    location: 'bedford',
    rand: Math.random(),
  },
];

export const multiRowData = [
  { flavor: 'Chocolate', price: '$8.00' },
  { flavor: 'Vanilla', price: '$4.00' },
  { flavor: 'Funfetti', price: '$6.00' },
  { price: '$3.00' },
];
